sampling:
  rate: 0.50   # 50% sampling â€“ zyada logs aayenge
  enabled: true

instrumentation:
  include_packages:
    - "com.example.springtest"
  exclude_packages:
    - "java."
    - "sun."
    - "jdk.internal"
    - "net.bytebuddy"

pinning_detection:
  enabled: true

overhead:
  circuit_breaker_threshold_ms: 1000